"""
This module is home to the FanCapabilities class
"""
from pyecobee.ecobee_object import EcobeeObject
from pyecobee.enumerations import FanSpeed

class FanCapabilities(EcobeeObject):
    """
    This class has been auto generated by scraping
    https://www.ecobee.com/home/developer/api/documentation/v1/objects/FanCapabilities.shtml

    Attribute names have been generated by converting ecobee property
    names from camelCase to snake_case.

    A getter property has been generated for each attribute.
    A setter property has been generated for each attribute whose value
    of READONLY is "no".

    An __init__ argument without a default value has been generated if
    the value of REQUIRED is "yes".
    An __init__ argument with a default value of None has been generated
    if the value of REQUIRED is "no".
    """

    __slots__ = ['_speed_options']

    attribute_name_map = {
        'speedOptions': 'speed_options',
        'speed_options': 'speedOptions',
    }

    attribute_type_map = {
        'speed_options': 'six.string',
    }

    def __init__(self, speed_options=None):
        """
        Construct a FanCapabilities instance
        """
        self._speed_options = speed_options

    @property
    def speed_options(self):
        return self._speed_options